name: "build-test"

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Import Code Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

    - name: Download Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v3
      with:
        bundle-id: codes.orj.Example-iOS
        issuer-id: ${{ vars.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ vars.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Build
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: ./Build

    - name: Upload TestFlight Build
      uses: Apple-Actions/upload-testflight-build@master
      with:
        app-path: .build/Artifacts/Example-iOS.ipa/Example-iOS.ipa
        issuer-id: ${{ vars.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ vars.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
